/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVentasRouteImport } from './routes/_authenticated/ventas'
import { Route as AuthenticatedNominaRouteImport } from './routes/_authenticated/nomina'
import { Route as AuthenticatedInventarioRouteImport } from './routes/_authenticated/inventario'
import { Route as AuthenticatedGastosRouteImport } from './routes/_authenticated/gastos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAjustesRouteImport } from './routes/_authenticated/ajustes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVentasRoute = AuthenticatedVentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNominaRoute = AuthenticatedNominaRouteImport.update({
  id: '/nomina',
  path: '/nomina',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventarioRoute = AuthenticatedInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGastosRoute = AuthenticatedGastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAjustesRoute = AuthenticatedAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gastos': typeof AuthenticatedGastosRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/nomina': typeof AuthenticatedNominaRoute
  '/ventas': typeof AuthenticatedVentasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gastos': typeof AuthenticatedGastosRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/nomina': typeof AuthenticatedNominaRoute
  '/ventas': typeof AuthenticatedVentasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/ajustes': typeof AuthenticatedAjustesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gastos': typeof AuthenticatedGastosRoute
  '/_authenticated/inventario': typeof AuthenticatedInventarioRoute
  '/_authenticated/nomina': typeof AuthenticatedNominaRoute
  '/_authenticated/ventas': typeof AuthenticatedVentasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ajustes'
    | '/dashboard'
    | '/gastos'
    | '/inventario'
    | '/nomina'
    | '/ventas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ajustes'
    | '/dashboard'
    | '/gastos'
    | '/inventario'
    | '/nomina'
    | '/ventas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/ajustes'
    | '/_authenticated/dashboard'
    | '/_authenticated/gastos'
    | '/_authenticated/inventario'
    | '/_authenticated/nomina'
    | '/_authenticated/ventas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ventas': {
      id: '/_authenticated/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof AuthenticatedVentasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nomina': {
      id: '/_authenticated/nomina'
      path: '/nomina'
      fullPath: '/nomina'
      preLoaderRoute: typeof AuthenticatedNominaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventario': {
      id: '/_authenticated/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthenticatedInventarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gastos': {
      id: '/_authenticated/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof AuthenticatedGastosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ajustes': {
      id: '/_authenticated/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AuthenticatedAjustesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAjustesRoute: typeof AuthenticatedAjustesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGastosRoute: typeof AuthenticatedGastosRoute
  AuthenticatedInventarioRoute: typeof AuthenticatedInventarioRoute
  AuthenticatedNominaRoute: typeof AuthenticatedNominaRoute
  AuthenticatedVentasRoute: typeof AuthenticatedVentasRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAjustesRoute: AuthenticatedAjustesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGastosRoute: AuthenticatedGastosRoute,
  AuthenticatedInventarioRoute: AuthenticatedInventarioRoute,
  AuthenticatedNominaRoute: AuthenticatedNominaRoute,
  AuthenticatedVentasRoute: AuthenticatedVentasRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
