// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbztytxaspltulphnwqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRienR5dHhhc3BsdHVscGhud3FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5ODUzMDUsImV4cCI6MjA5MDU2MTMwNX0.ZMeMhLJ36iCSaUhf1zx_VKtGw8cGz7CwYjgd-zLKocU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});